#!/bin/bash
echo "your administrator password will be ask to copy shnote script to you /bin folder\n"
sudo cp -u shnote /bin/shnote
echo -e  "shnote has been installed in /bin/shnote\n"
echo -e  "usage :\n"
echo -e  "shnote My new cool idea\n"
echo -e "for help you can type shnote --help"
