#! /bin/bash

## parametres ##
takenotewith="nano"
# notes will be saved here
notesdir="/home/noone/.shnote"
#extension des fichiers
extension=$RANDOM$RANDOM

cd $notesdir
if [ "$1" == "--list" ]; then
  clear
  cat $(ls -tpar | grep -v /) | fold -w 80
  echo -e "\n"
  exit 1
fi
if [ "$1" == "--help" ]; then
  cat << EOF
  shnote v1.0 : Take note from the terminal
  Usage : note [MY NOTE TITLE]

  options:
    --help display this help
    --list list all saved notesdir
EOF
exit;
fi
TITRE=$*
Snomfichier=$(echo $* | cut -c 1-18)
nomfichier=$(echo "${Snomfichier// /-}").$extension
cheminfichier=$notesdir/$nomfichier
echo -e "\n new note : "$cheminfichier
touch $cheminfichier
ligne(){
  for i in {1..80}; do echo -n ${1}>>$nomfichier; done
}

echo -e "\n"
ligne "="
echo -e "\n $TITRE" >> $cheminfichier
echo -e "\n Date : $(date +%d-%B-%y)" >> $cheminfichier
ligne "="


echo -e "\n\n\n\n\n\n" >> $cheminfichier
ligne "."
echo -e "\nTags :" >> $cheminfichier
ligne "."
echo -e "\n" >> $cheminfichier

$takenotewith -nmw --clear-window-state $cheminfichier
cat << EOF

                    OK!
            _________________
            |# :           : #|
            |  :           :  |
            |  :   NOTES   :  |
            |  :           :  |
            |  :___________:  |
            |     _________   |
            |    | __      |  |
            |    ||  |     |  |
            \____||__|_____|__|
EOF
echo -e "\n\n"
