#! /bin/bash
# shnote by Philippe Benoist
# www.shantee.com
################################################################################

## a couple of parameters you could change according to your needs
#the name of your favorite text editor
takenotewith="nano"
#path of the directory in which your notes will be saved
#no trailing slash at the end
notesdir="$HOME/.shnote"

################################################################################

extension=$RANDOM$RANDOM
titre=$*
titreredui=$(echo $* | cut -c 1-18)
nomfichier=$(echo "${titreredui// /-}").$extension
cheminfichier=$notesdir/$nomfichier
mkdir -p $notesdir


## functions
ligne(){
  for i in {1..80}; do echo -n ${1}>>$nomfichier; done
}
countfiles(){
  ls -1q * | wc -l
}
do_list(){
  cd $notesdir
  clear
  cat $(ls -tpar | grep -v /) | fold -w 80
  echo -e "\n"
  exit 1;
}
do_help(){
  echo -e "shnote v1.0 : Take note from the terminal\n"
  echo -e "Usage : note [MY NOTE TITLE]\n"
  echo -e "\noptions:\n\t --help : display this help\n\t --list : list all saved notes\n"
}


do_note(){
  if [ -z "$1"];  then
    echo "No argument supplied"
  else
    cd $notesdir
    echo -e "\n new note : "$cheminfichier
    touch $cheminfichier
    ligne "="
    echo -e "\n $titre" >> $cheminfichier
    echo -e "\n Date : $(date +%d-%B-%y)" >> $cheminfichier
    ligne "="

    echo -e "\n\n\n\n\n\n" >> $cheminfichier
    ligne "."
    echo -e "\nTags :" >> $cheminfichier
    ligne "."
    echo -e "\n" >> $cheminfichier
#atom -nmw --clear-window-state
    $takenotewith  $cheminfichier
cat << EOF

                        OK!
                _________________
                |# :           : #|
                |  :           :  |
                |  :   NOTES   :  |
                |  :           :  |
                |  :___________:  |
                |     _________   |
                |    | __      |  |
                |    ||  |     |  |
                \____||__|_____|__|
EOF
  fi
}
case "$1" in
 --list) do_list
 ;;
 --help) do_help
 exit 1;
 ;;
 *) do_note
 ;;
esac
